version: "3.8"
services:
    # database:
    #     image: mysql:5.7
    #     ports:
    #     - target: 3306
    #       published: 3306

    ser1:
        build: ./Service1
        image: ddiazsouto/ser1:latest
        ports:
        - target: 5500
          published: 5500        
          protocol: tcp
    # depends_on:
    #     - "database"

    ser4:
        build: ./Service4
        image: ddiazsouto/ser4:latest
        ports:
        - target: 5050
          published: 5050        
          protocol: tcp
    
    ser2:
        build: ./Service2
        image: ddiazsouto/ser2:latest
        ports:
        - target: 5000
          published: 5000
          protocol: tcp

    ser3:
        build: ./Service3
        image: ddiazsouto/ser3:latest
        ports:
        - target: 5005
          published: 5005
          protocol: tcp


